### ISSUE TITLE
Seems the API is down

### ISSUE THREAD

**Issue by robertkowalski** [zoepage/just-relax#3]
I get a blank screen after clicking on the button in the dashboard labeled "there is always time for vacation!" 

It seems the API is down: http://justrelax.rrbone.io/booking/holiday?from=2016-02-05&to=2016-02-15&location=&budget=10000 404 (Not Found)

**Comment by badboy** [comment]
You should atleast give us a hint where you want to travel, so we can fetch something right for you ;)
